import 'https://unpkg.com/scrollreveal'

import './js/header.js'
import './js/projetos.js'
import './js/scroll.js'
import './js/certificados.js'
import './js/footer.js'
import './js/texto-deco.js'
import './js/swiper.js'
import './js/translate.js'
